# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('Login_Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.ItemList')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_Store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Customer')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.Price')),
            ],
        ),
    ]
