# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='preference',
            field=models.CharField(max_length=20),
        ),
    ]
